"""Local types for the partially untyped torchaudio dependency."""

from typing import Any

class AudioMetaData:
    @property
    def sample_rate(self) -> int: ...
    @property
    def num_frames(self) -> int: ...
    @property
    def num_channels(self) -> int: ...

def info(filepath: str) -> AudioMetaData: ...
def load(filepath: str) -> tuple[Any, int]: ...
