"""Local types for the partially untyped torchaudio dependency."""

from typing import Any

class AudioMetaData:
    @property
    def sample_rate(self) -> int: ...
    @property
    def num_frames(self) -> int: ...
    @property
    def num_channels(self) -> int: ...

def info(filepath: str) -> AudioMetaData: ...
def load(filepath: str) -> tuple[Any, int]: ...

class functional:
    @staticmethod
    def resample(waveform: Any, orig_freq: int, new_freq: int) -> Any: ...
